### ISSUE TITLE
Core dump when adding module in module manager

### ISSUE THREAD

**Issue by marrem** [cropinghigh/sdrpp-tetra-demodulator#11]
Running:

SDR++, build from commit 794d6ff5acf66d5da7fb7fceba7b952c95305960

At Linux ubuntuvm01 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 12:53:29 UTC 2 aarch64 aarch64 aarch64 GNU/Linux723834177.937404@[298925611740750] (UTM):* SLSGetNextEventRecordInternal: loc (568.1, 853.8) conn 0x149197 MouseMoved win 0x5622 (click 0)

Running in UTM/qemu on Mac M1

Built the sdr-tetra-demodulator from source.

When installing in SDR++ module manager, I get:

[09/12/2023 18:16:06.000] [INFO] Running post-init for Scanner
[09/12/2023 18:16:06.000] [INFO] Running post-init for SoapySDR Source
[09/12/2023 18:16:06.000] [INFO] Running post-init for SpyServer Source
[09/12/2023 18:16:06.000] [INFO] Ready.
[Resamp] predec: 8192, interp: 9, decim: 2, inacc: 0.000000%, taps: 684
Segmentation fault (core dumped)

[_usr_bin_sdrpp.1000.crash.gz](https://github.com/cropinghigh/sdrpp-tetra-demodulator/files/13625093/_usr_bin_sdrpp.1000.crash.gz)

**Comment by marrem** [comment]
I have added the module 'manually' to the config.json.
Started SDR++, first time another core dump. Second time and from then on, no problems....

<img width="387" alt="afbeelding" src="https://github.com/cropinghigh/sdrpp-tetra-demodulator/assets/2941173/f40d1a73-f38e-4778-af55-3cb5a239ef19">

Don't know why the adding from module manager doesn't work.

**Comment by cropinghigh** [comment]
Unfortunately, crash report isn't very informative. Can you try to catch that segfault's backtrace starting sdr++ with gdb?

**Comment by marrem** [comment]
How do I do that? Do I need to recompile sdr++ or the tetra-demodulator with debug symbols enabled for that?

**Comment by cropinghigh** [comment]
I think i caught it too
`#0  0x00007fffd06c3875 in ?? () from /usr/lib/libtalloc.so.2
#1  0x00007fffd06c3d62 in _talloc_zero () from /usr/lib/libtalloc.so.2
#2  0x00007fffc20797b6 in dsp::osmotetradec::init (this=this@entry=0x555561008da8, in=in@entry=0x555561008c38) at /drive/data/Linux/TEMP/builds/sdrpp-tetra-demodulator/src/osmotetra_dec.h:35
#3  0x00007fffc20815e6 in TetraDemodulatorModule::TetraDemodulatorModule (this=0x555561001840, name="td") at /drive/data/Linux/TEMP/builds/sdrpp-tetra-demodulator/src/main.cpp:74
#4  0x00007fffc20708b4 in _CREATE_INSTANCE_ (name="td") at /drive/data/Linux/TEMP/builds/sdrpp-tetra-demodulator/src/main.cpp:315
#5  0x00007ffff79b7251 in ModuleManager::createInstance(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
   from /usr/lib/libsdrpp_core.so
#6  0x00007ffff78bebbe in MainWindow::init() () from /usr/lib/libsdrpp_core.so
#7  0x00007ffff788f784 in sdrpp_main(int, char**) () from /usr/lib/libsdrpp_core.so
#8  0x00007ffff7645cd0 in ?? () from /usr/lib/libc.so.6
#9  0x00007ffff7645d8a in __libc_start_main () from /usr/lib/libc.so.6
#10 0x0000555555555055 in ?? ()
`

**Comment by cropinghigh** [comment]
206ab9f probably fixed that

**Comment by marrem** [comment]
Thanks. Somehow SDR++ sometimes crashes when starting. But when retrying it starts and runs without issues. So I have been able to use the plugin. It works fine. But I will rebuild the plugin and see if I can start SDR++ now without crashes.
