### ISSUE TITLE
SDRpp crashes after signal lock

### ISSUE THREAD

**Issue by damige** [cropinghigh/sdrpp-tetra-demodulator#31]
When locking onto any tetra signal SDRpp crashes straight away.
This is the status of the module, when the crash occurs.
![img](https://github.com/user-attachments/assets/c44836b3-c274-444a-bf94-d14ae06e6630)

Module was installed on arch through the AUR. for hardware a hackrf was used.

**Comment by damige** [comment]
just once got this different error, related?

`malloc(): smallbin double linked list corrupted

Thread 1 "sdrpp" received signal SIGABRT, Aborted.
0x00007ffff76a53f4 in ?? () from /usr/lib/libc.so.6
(gdb) backtrace
#0  0x00007ffff76a53f4 in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff764c120 in raise () from /usr/lib/libc.so.6
#2  0x00007ffff76334c3 in abort () from /usr/lib/libc.so.6
#3  0x00007ffff7634354 in ?? () from /usr/lib/libc.so.6
#4  0x00007ffff76af765 in ?? () from /usr/lib/libc.so.6
#5  0x00007ffff76b310c in ?? () from /usr/lib/libc.so.6
#6  0x00007ffff76b4fae in calloc () from /usr/lib/libc.so.6
#7  0x00007fffc5fcade7 in ?? () from /usr/lib/libgallium-24.3.1-arch1.1.so
#8  0x00007fffc5d00c71 in ?? () from /usr/lib/libgallium-24.3.1-arch1.1.so
#9  0x00007fffc56e4637 in ?? () from /usr/lib/libgallium-24.3.1-arch1.1.so
#10 0x00007fffc563580b in dri_flush () from /usr/lib/libgallium-24.3.1-arch1.1.so
#11 0x00007fffd69394c9 in ?? () from /usr/lib/libEGL_mesa.so.0
#12 0x00007fffd692e99b in ?? () from /usr/lib/libEGL_mesa.so.0
#13 0x00007fffd6921db9 in ?? () from /usr/lib/libEGL_mesa.so.0
#14 0x00007ffff79a423b in backend::render (vsync=vsync@entry=true) at /usr/src/debug/sdrpp-git/sdrpp/core/backends/glfw/backend.cpp:219
#15 0x00007ffff79a5c5f in backend::renderLoop () at /usr/src/debug/sdrpp-git/sdrpp/core/backends/glfw/backend.cpp:288
#16 0x00007ffff786fdec in sdrpp_main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/sdrpp-git/sdrpp/core/src/core.cpp:398
#17 0x00007ffff7634e08 in ?? () from /usr/lib/libc.so.6
#18 0x00007ffff7634ecc in __libc_start_main () from /usr/lib/libc.so.6
#19 0x0000555555555055 in _start ()
(gdb) `

**Comment by damige** [comment]
Tried the old linux-lts kernel and the latest one, switched desktop environments and resolutions (as it crashed once with mesa), recompiled this module with O1, but i have no idea what is going wrong, or how/if its working for other people.

**Comment by cropinghigh** [comment]
Maybe try out previous commits?

**Comment by damige** [comment]
Ther are some warnings while compiling. related?

```
==> Making package: sdrpp-tetra-demodulator-git r18.9e3a757-1 (Wed Dec 11 21:38:33 2024)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating sdrpp-tetra-demodulator git repo...
==> Validating source files with md5sums...
    sdrpp-tetra-demodulator ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of sdrpp-tetra-demodulator git repo...
Cloning into 'sdrpp-tetra-demodulator'...
done.
==> Starting pkgver()...
==> Updated version: sdrpp-tetra-demodulator-git r100.d643db5-1
==> Sources are ready.
==> Making package: sdrpp-tetra-demodulator-git r100.d643db5-1 (Wed Dec 11 21:38:35 2024)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Starting build()...
Deleting /home/damige/.cache/yay/sdrpp-tetra-demodulator-git/src/sdrpp-tetra-demodulator/src/decoder/etsi_codec-patches/../codec ...
Creating /home/damige/.cache/yay/sdrpp-tetra-demodulator-git/src/sdrpp-tetra-demodulator/src/decoder/etsi_codec-patches/../codec ...
Downloading http://www.etsi.org/deliver/etsi_en/300300_300399/30039502/01.03.01_60/en_30039502v010301p0.zip ...
Checking MD5SUM ...
Unpacking ZIP ...
Archive:  /home/damige/.cache/yay/sdrpp-tetra-demodulator-git/src/sdrpp-tetra-demodulator/src/decoder/etsi_codec-patches/etsi_tetra_codec.zip
  inflating: c-word/c_word.win       
  inflating: c-word/c_word_a.doc     
  inflating: c-word/c_word_b.doc     
  inflating: c-word/c_word_c.doc     
  inflating: c-word/c_word_d.doc     
  inflating: c-word/c_word_e.doc     
  inflating: c-word/c_word_f.doc     
  inflating: amr-code/arrays.h       
  inflating: amr-code/arrays.tab     
  inflating: amr-code/arrays_amr475.tab  
  inflating: amr-code/arrays_tetra.tab  
  inflating: amr-code/ccoder.c       
  inflating: amr-code/ccod_tet.c     
  inflating: amr-code/cdecoder.c     
  inflating: amr-code/cdec_tet.c     
  inflating: amr-code/channel.h      
  inflating: amr-code/const.tab      
  inflating: amr-code/const_amr475.tab  
  inflating: amr-code/const_tetra.tab  
  inflating: amr-code/globals.c      
  inflating: amr-code/globals.h      
  inflating: amr-code/init_params.c  
  inflating: amr-code/makefile       
  inflating: amr-code/source.h       
  inflating: amr-code/sub_cc.c       
  inflating: amr-code/sub_cd.c       
  inflating: amr-code/tetra_op.c     
  inflating: c-code/arrays.tab       
  inflating: c-code/ccoder.c         
  inflating: c-code/ccod_tet.c       
  inflating: c-code/cdecoder.c       
  inflating: c-code/cdec_tet.c       
  inflating: c-code/channel.h        
  inflating: c-code/clsp_334.tab     
  inflating: c-code/const.tab        
  inflating: c-code/ener_qua.tab     
  inflating: c-code/fbas_tet.c       
  inflating: c-code/fexp_tet.c       
  inflating: c-code/fmat_tet.c       
  inflating: c-code/grid.tab         
  inflating: c-code/inv_sqrt.tab     
  inflating: c-code/lag_wind.tab     
  inflating: c-code/log2.tab         
  inflating: c-code/makefile         
  inflating: c-code/pow2.tab         
  inflating: c-code/scoder.c         
  inflating: c-code/scod_tet.c       
  inflating: c-code/sdecoder.c       
  inflating: c-code/sdec_tet.c       
  inflating: c-code/source.h         
  inflating: c-code/sub_cc.c         
  inflating: c-code/sub_cd.c         
  inflating: c-code/sub_dsp.c        
  inflating: c-code/sub_sc_d.c       
  inflating: c-code/tetra_op.c       
  inflating: c-code/window.tab       
Contents of /home/damige/.cache/yay/sdrpp-tetra-demodulator-git/src/sdrpp-tetra-demodulator/src/decoder/etsi_codec-patches/../codec:
total 20K
drwxr-xr-x 5 damige damige 4.0K Dec 11 21:38 .
drwxr-xr-x 5 damige damige 4.0K Dec 11 21:38 ..
drwxr-xr-x 2 damige damige 4.0K Dec 11 21:38 amr-code
drwxr-xr-x 2 damige damige 4.0K Dec 11 21:38 c-code
drwxr-xr-x 2 damige damige 4.0K Dec 11 21:38 c-word
Applying Patches ...
total 404K
drwxr-xr-x 2 damige damige 4.0K Dec 11 21:38 .
drwxr-xr-x 5 damige damige 4.0K Dec 11 21:38 ..
-rw-r--r-- 1 damige damige 1.4K Dec 11 21:38 README
-rwxr-xr-x 1 damige damige  988 Dec 11 21:38 download_and_patch.sh
-rw-r--r-- 1 damige damige 353K Dec 11 21:38 etsi_tetra_codec.zip
-rw-r--r-- 1 damige damige 1.2K Dec 11 21:38 filename-case.patch
-rw-r--r-- 1 damige damige  836 Dec 11 21:38 fix_64bit.patch
-rw-r--r-- 1 damige damige 5.2K Dec 11 21:38 log_stderr.patch
-rw-r--r-- 1 damige damige 1.5K Dec 11 21:38 makefile-cleanups.patch
-rw-r--r-- 1 damige damige 6.6K Dec 11 21:38 round_private.patch
-rw-r--r-- 1 damige damige   97 Dec 11 21:38 series
makefile-cleanups.patch
fix_64bit.patch
round_private.patch
filename-case.patch
log_stderr.patch
=> Applying patch '/home/damige/.cache/yay/sdrpp-tetra-demodulator-git/src/sdrpp-tetra-demodulator/src/decoder/etsi_codec-patches/makefile-cleanups.patch'...
patching file amr-code/makefile
patching file c-code/makefile
=> Applying patch '/home/damige/.cache/yay/sdrpp-tetra-demodulator-git/src/sdrpp-tetra-demodulator/src/decoder/etsi_codec-patches/fix_64bit.patch'...
patching file amr-code/source.h
patching file c-code/source.h
=> Applying patch '/home/damige/.cache/yay/sdrpp-tetra-demodulator-git/src/sdrpp-tetra-demodulator/src/decoder/etsi_codec-patches/round_private.patch'...
patching file amr-code/channel.h
patching file amr-code/source.h
Hunk #1 succeeded at 165 (offset 1 line).
patching file amr-code/tetra_op.c
patching file c-code/channel.h
patching file c-code/source.h
Hunk #1 succeeded at 165 (offset 1 line).
patching file c-code/sub_dsp.c
patching file c-code/sub_sc_d.c
patching file c-code/tetra_op.c
=> Applying patch '/home/damige/.cache/yay/sdrpp-tetra-demodulator-git/src/sdrpp-tetra-demodulator/src/decoder/etsi_codec-patches/filename-case.patch'...
patching file amr-code/init_params.c
=> Applying patch '/home/damige/.cache/yay/sdrpp-tetra-demodulator-git/src/sdrpp-tetra-demodulator/src/decoder/etsi_codec-patches/log_stderr.patch'...
patching file c-code/cdecoder.c
patching file c-code/sdecoder.c
Done!
-- The C compiler identification is GNU 14.2.1
-- The CXX compiler identification is GNU 14.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (0.5s)
-- Generating done (0.0s)
-- Build files have been written to: /home/damige/.cache/yay/sdrpp-tetra-demodulator-git/src/sdrpp-tetra-demodulator/build
[  6%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/cdec_tet.c.o
[  6%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/fmat_tet.c.o
[ 11%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/fbas_tet.c.o
[ 11%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/fexp_tet.c.o
[ 13%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/sub_dsp.c.o
[ 15%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/sub_cd.c.o
[ 15%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/sdec_tet.c.o
[ 17%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/tetra_op.c.o
[ 20%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/codec/c-code/sub_sc_d.c.o
[ 22%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/hurdle.c.o
[ 24%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/taa1.c.o
[ 28%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/tea2.c.o
[ 28%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/tea1.c.o
[ 31%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/tea3.c.o
[ 33%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/crypto/tetra_crypto.c.o
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
[ 37%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/lower_mac/osmo_conv.c.o
[ 37%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/lower_mac/crc_simple.c.o
[ 40%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/lower_mac/tch_reordering.c.o
[ 42%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/lower_mac/tetra_conv_enc.c.o
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
[ 44%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/lower_mac/tetra_interleave.c.o
[ 48%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/lower_mac/tetra_rm3014.c.o
[ 46%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/lower_mac/tetra_lower_mac.c.o
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
[ 51%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/lower_mac/tetra_scramb.c.o
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
[ 53%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/lower_mac/viterbi.c.o
[ 55%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/lower_mac/viterbi_cch.c.o
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
[ 57%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/lower_mac/viterbi_tch.c.o
[ 62%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/phy/tetra_burst.c.o
[ 62%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/phy/tetra_burst_sync.c.o
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
[ 64%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/tetra_cmce_pdu.c.o
[ 66%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/tetra_common.c.o
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
[ 71%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/tetra_mac_pdu.c.o
[ 71%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/tetra_mle.c.o
[ 73%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/tetra_mle_pdu.c.o
[ 75%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/tetra_mm_pdu.c.o
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
[ 77%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/tetra_tdma.c.o
[ 80%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/tetra_upper_mac.c.o
[ 82%] Building C object CMakeFiles/tetra_demodulator.dir/src/decoder/src/tetra_sndcp_pdu.c.o
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
[ 84%] Building CXX object CMakeFiles/tetra_demodulator.dir/src/dsp/bit_unpacker.cpp.o
[ 86%] Building CXX object CMakeFiles/tetra_demodulator.dir/src/dsp/complex_fd.cpp.o
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
cc1: warning: command-line option ‘-std=c++17’ is valid for C++/ObjC++ but not for C
[ 91%] Building CXX object CMakeFiles/tetra_demodulator.dir/src/dsp/dqpsk_sym_extr.cpp.o
[ 91%] Building CXX object CMakeFiles/tetra_demodulator.dir/src/dsp/fll.cpp.o
[ 93%] Building CXX object CMakeFiles/tetra_demodulator.dir/src/dsp/pi4dqpsk.cpp.o
[ 95%] Building CXX object CMakeFiles/tetra_demodulator.dir/src/dsp/pi4dqpsk_costas.cpp.o
[ 97%] Building CXX object CMakeFiles/tetra_demodulator.dir/src/main.cpp.o
[100%] Linking CXX shared library tetra_demodulator.so
/usr/src/debug/sdrpp-tetra-demodulator-git/sdrpp-tetra-demodulator/src/decoder/codec/c-code/channel.h:141:8: warning: type of ‘L_deposit_l’ does not match original declaration [-Wlto-type-mismatch]
  141 | Word32 L_deposit_l(Word16 var1);          /* 16 bit var1 -> LSB,  2 */
      |        ^
/usr/src/debug/sdrpp-tetra-demodulator-git/sdrpp-tetra-demodulator/src/decoder/codec/c-code/tetra_op.c:494:8: note: return value type mismatch
  494 | Word32 L_deposit_l(Word16 var1)
      |        ^
/usr/src/debug/sdrpp-tetra-demodulator-git/sdrpp-tetra-demodulator/src/decoder/codec/c-code/tetra_op.c:494:8: note: ‘L_deposit_l’ was previously declared here
/usr/src/debug/sdrpp-tetra-demodulator-git/sdrpp-tetra-demodulator/src/decoder/codec/c-code/tetra_op.c:494:8: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
/usr/src/debug/sdrpp-tetra-demodulator-git/sdrpp-tetra-demodulator/src/decoder/codec/c-code/channel.h:126:8: warning: type of ‘extract_h’ does not match original declaration [-Wlto-type-mismatch]
  126 | Word16 extract_h(Word32 L_var1);          /* Extract high,        1 */
      |        ^
/usr/src/debug/sdrpp-tetra-demodulator-git/sdrpp-tetra-demodulator/src/decoder/codec/c-code/tetra_op.c:282:8: note: type mismatch in parameter 1
  282 | Word16 extract_h(Word32 L_var1)
      |        ^
/usr/src/debug/sdrpp-tetra-demodulator-git/sdrpp-tetra-demodulator/src/decoder/codec/c-code/tetra_op.c:282:8: note: ‘extract_h’ was previously declared here
/usr/src/debug/sdrpp-tetra-demodulator-git/sdrpp-tetra-demodulator/src/decoder/codec/c-code/tetra_op.c:282:8: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
/usr/src/debug/sdrpp-tetra-demodulator-git/sdrpp-tetra-demodulator/src/decoder/codec/c-code/channel.h:149:8: warning: type of ‘L_shl’ does not match original declaration [-Wlto-type-mismatch]
  149 | Word32 L_shl(Word32 L_var1, Word16 var2); /* Long shift left,     2 */
      |        ^
/usr/src/debug/sdrpp-tetra-demodulator-git/sdrpp-tetra-demodulator/src/decoder/codec/c-code/tetra_op.c:860:8: note: return value type mismatch
  860 | Word32 L_shl(Word32 L_var1, Word16 var2)
      |        ^
/usr/src/debug/sdrpp-tetra-demodulator-git/sdrpp-tetra-demodulator/src/decoder/codec/c-code/tetra_op.c:860:8: note: ‘L_shl’ was previously declared here
/usr/src/debug/sdrpp-tetra-demodulator-git/sdrpp-tetra-demodulator/src/decoder/codec/c-code/tetra_op.c:860:8: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
[100%] Built target tetra_demodulator
==> Entering fakeroot environment...
==> Starting package()...
[  2%] Linking CXX shared library tetra_demodulator.so
/usr/src/debug/sdrpp-tetra-demodulator-git/sdrpp-tetra-demodulator/src/decoder/codec/c-code/channel.h:141:8: warning: type of ‘L_deposit_l’ does not match original declaration [-Wlto-type-mismatch]
  141 | Word32 L_deposit_l(Word16 var1);          /* 16 bit var1 -> LSB,  2 */
      |        ^
/usr/src/debug/sdrpp-tetra-demodulator-git/sdrpp-tetra-demodulator/src/decoder/codec/c-code/tetra_op.c:494:8: note: return value type mismatch
  494 | Word32 L_deposit_l(Word16 var1)
      |        ^
/usr/src/debug/sdrpp-tetra-demodulator-git/sdrpp-tetra-demodulator/src/decoder/codec/c-code/tetra_op.c:494:8: note: ‘L_deposit_l’ was previously declared here
/usr/src/debug/sdrpp-tetra-demodulator-git/sdrpp-tetra-demodulator/src/decoder/codec/c-code/tetra_op.c:494:8: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
/usr/src/debug/sdrpp-tetra-demodulator-git/sdrpp-tetra-demodulator/src/decoder/codec/c-code/channel.h:126:8: warning: type of ‘extract_h’ does not match original declaration [-Wlto-type-mismatch]
  126 | Word16 extract_h(Word32 L_var1);          /* Extract high,        1 */
      |        ^
/usr/src/debug/sdrpp-tetra-demodulator-git/sdrpp-tetra-demodulator/src/decoder/codec/c-code/tetra_op.c:282:8: note: type mismatch in parameter 1
  282 | Word16 extract_h(Word32 L_var1)
      |        ^
/usr/src/debug/sdrpp-tetra-demodulator-git/sdrpp-tetra-demodulator/src/decoder/codec/c-code/tetra_op.c:282:8: note: ‘extract_h’ was previously declared here
/usr/src/debug/sdrpp-tetra-demodulator-git/sdrpp-tetra-demodulator/src/decoder/codec/c-code/tetra_op.c:282:8: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
/usr/src/debug/sdrpp-tetra-demodulator-git/sdrpp-tetra-demodulator/src/decoder/codec/c-code/channel.h:149:8: warning: type of ‘L_shl’ does not match original declaration [-Wlto-type-mismatch]
  149 | Word32 L_shl(Word32 L_var1, Word16 var2); /* Long shift left,     2 */
      |        ^
/usr/src/debug/sdrpp-tetra-demodulator-git/sdrpp-tetra-demodulator/src/decoder/codec/c-code/tetra_op.c:860:8: note: return value type mismatch
  860 | Word32 L_shl(Word32 L_var1, Word16 var2)
      |        ^
/usr/src/debug/sdrpp-tetra-demodulator-git/sdrpp-tetra-demodulator/src/decoder/codec/c-code/tetra_op.c:860:8: note: ‘L_shl’ was previously declared here
/usr/src/debug/sdrpp-tetra-demodulator-git/sdrpp-tetra-demodulator/src/decoder/codec/c-code/tetra_op.c:860:8: note: code may be misoptimized unless ‘-fno-strict-aliasing’ is used
[100%] Built target tetra_demodulator
Install the project...
-- Install configuration: ""
-- Installing: /home/damige/.cache/yay/sdrpp-tetra-demodulator-git/pkg/sdrpp-tetra-demodulator-git/usr/lib/sdrpp/plugins/tetra_demodulator.so
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issues...
==> Creating package "sdrpp-tetra-demodulator-git"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Creating package "sdrpp-tetra-demodulator-git-debug"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: sdrpp-tetra-demodulator-git r100.d643db5-1 (Wed Dec 11 21:38:47 2024)
==> Cleaning up...

```

**Comment by damige** [comment]
> Maybe try out previous commits?

will try that

**Comment by cropinghigh** [comment]
Hmm... There shouldnt be any warnings about codec. Maybe it was changed on the server...

**Comment by damige** [comment]
built commit "aac86252f8188a890685d89b517ffa3c2f179ab4"

same crash timing: GDB shows:


```
Thread 149 "sdrpp" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff067fc6c0 (LWP 119501)]
0x00007fff671aaa62 in tetra_burst_rx_cb () from /usr/lib/sdrpp/plugins/tetra_demodulator.so
(gdb) backtrace
#0  0x00007fff671aaa62 in tetra_burst_rx_cb () from /usr/lib/sdrpp/plugins/tetra_demodulator.so
#1  0x00007fff671aafa6 in tetra_burst_sync_in () from /usr/lib/sdrpp/plugins/tetra_demodulator.so
#2  0x00007fff671c483d in dsp::osmotetradec::run() () from /usr/lib/sdrpp/plugins/tetra_demodulator.so
#3  0x00007ffff7968a59 in dsp::block::workerLoop (this=0x5555698e6e08) at /usr/src/debug/sdrpp-git/sdrpp/core/src/signal_path/../dsp/buffer/../block.h:68
#4  0x00007ffff6ae1c34 in std::execute_native_thread_routine (__p=0x55555976f790) at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/thread.cc:104
#5  0x00007ffff76a339d in ?? () from /usr/lib/libc.so.6
#6  0x00007ffff772849c in ?? () from /usr/lib/libc.so.6
(gdb) 
```

**Comment by damige** [comment]
> Hmm... There shouldnt be any warnings about codec. Maybe it was changed on the server...

let me know if there is anything i can test

**Comment by typhoniks** [comment]
same problem here, using old version of the plugin didn't work so far, will update if i found the problem

**Comment by typhoniks** [comment]
Problem presisted even thought tested with older version of the Plugin

The problem is : HackRF

When i used RTL-SDR the SDR++ wasnt crashing and working fine !

**Comment by FQQD** [comment]
Hey there,
I was playing around with this as well, and for me it crashes after a few seconds after putting the playhead over a signal, or sometimes after ~10 seconds of playing nothing. The window freezes and CPU usage goes up, and then it closes.
These are the settings when crashing:

![Image](https://github.com/user-attachments/assets/0fe3545f-61bd-4ea4-80da-4b717644a120)


Here's the terminal output when running sdrpp:
`RTL-SDR Blog V4 Detected
[05/06/2025 19:03:34.000] [INFO] RTL-SDR Sample Rate: 2400000.000000
Disabled direct sampling mode
[05/06/2025 19:03:34.000] [INFO] RTLSDRSourceModule 'RTL-SDR Source': Start!
[05/06/2025 19:03:35.000] [INFO] RTLSDRSourceModule 'RTL-SDR Source': Tune: 429140000.000000!
Illegal instruction (core dumped)`

Sorry if I got anything wrong or if this is unrelated to this issue, I'm fairly new to this.

**Comment by cropinghigh** [comment]
Try getting the backtrace with GDB

**Comment by joltcan** [comment]
Root cause found (with AddressSanitizer): three heap-buffer-overflows in the decoder's sync path**

I hit this same crash — instant SIGSEGV on signal lock with a **HackRF**, while lower-rate SDRs were fine. Built the module with `-fsanitize=address` and traced it. It's not the demod/VOLK per se; that's a *symptom*. The actual cause is several out-of-bounds accesses in the osmo-tetra sync/bit-accounting code that only trigger once `bitbuf[]` fills up while hunting for sync — which happens with HackRF's noisier 8-bit input but not with a cleaner, lower-rate source. That's why it looks SDR-specific.

**The overflows (in order ASAN caught them):**

1. `tetra_find_train_seq()` — `src/decoder/src/phy/tetra_burst.c`
   The scan reads `cur[FILTER_LOOKAHEAD_LEN-1]` (i.e. `cur[21]`) each iteration, but the loop bound is `cur < in + end_of_in`, so the lookahead reads up to 20 bytes **past** the search buffer:
   ```
   ERROR: AddressSanitizer: heap-buffer-overflow READ of size 1
     #0 tetra_find_train_seq  src/decoder/src/phy/tetra_burst.c:296
     #1 tetra_burst_sync_in   src/decoder/src/phy/tetra_burst_sync.c:90
   0 bytes after a 4120-byte region (the tetra_rx_state)
   ```
   Fix: stop the loop early enough that the lookahead stays in bounds:
   ```c
   for (cur = in; cur + (FILTER_LOOKAHEAD_LEN-1) < in + end_of_in; cur++) {
   ```

2. `tetra_burst_sync_in()` `RX_S_KNOW_FSTART` — `src/decoder/src/phy/tetra_burst_sync.c`
   `offset = next_frame_start_bitnum - bitbuf_start_bitnum` can go negative/inconsistent, making `bits_remaining = bits_in_buf - offset` larger than the buffer and overflowing the `memmove`:
   ```
   ERROR: AddressSanitizer: heap-buffer-overflow READ of size 4818 in memmove
     #1 tetra_burst_sync_in   src/decoder/src/phy/tetra_burst_sync.c:115
   ```
   Fix: validate and resync if the accounting is inconsistent:
   ```c
   if (offset < 0 || bits_remaining < 0 ||
       (unsigned int)bits_remaining > sizeof(trs->bitbuf)) {
       trs->state = RX_S_UNLOCKED;
       trs->bitbuf_start_bitnum += trs->bits_in_buf;
       trs->bits_in_buf = 0;
       return len;
   }
   ```

3. Defensive guards in the same family: `make_bitbuf_space()` underflow/clamp so the append `memcpy` can never write past `bitbuf[]`; feeding the synchronizer in ≤2048-bit chunks in `osmotetra_dec.h::process()`; and bounding the clock-recovery loop index in `complex_fd.cpp` (a divergent PLL could read before `buffer[]` or overrun `out[]`).

With all of these, ASAN runs **clean through lock → decode → voice** on HackRF.

**Reproduce:** build with `-fsanitize=address -g -O1` (and `CMAKE_SHARED_LINKER_FLAGS=-fsanitize=address`), then
`ASAN_OPTIONS=halt_on_error=1:detect_leaks=0 LD_PRELOAD=$(gcc -print-file-name=libasan.so) sdrpp`, and lock onto any TETRA signal.

Branch with the fixes: https://github.com/joltcan/sdrpp-tetra-demodulator/tree/fix-hackrf-heap-overflows (commit `860a6c7`). 

Yes, I vibe coded this with Claude to help me find the issue, hope that's ok.
